### ISSUE TITLE
pod dashboard link incorrect

### ISSUE THREAD

**Issue by nopzor1200** [raintank/kubernetes-app#1]
(This app is installed on our internal g-m).

If you log in there, and try to click on a node dashboard, it works fine and the Dashboard loads.

However, if you try to click on a pod dashboard, the Dashboard does not load. From what I can tell, it's specifying a template variable for an incorrect node.

**Comment by nopzor1200** [comment]
I guess I'm wrong, some pod dashboards work and some pod dashboards do not.

**Comment by woodsaj** [comment]
the links look correct to me, there is just only data for 1 of the kubernetes nodes due to snap kill the collection tasks
