### ISSUE TITLE
Feature Request: Support OpenTSDB as a backend

### ISSUE THREAD

**Issue by jaredledvina** [raintank/kubernetes-app#26]
(If this isn't the proper place to raise feature request feel free to close this out)

Hi! This plugin looks amazing but, as the README states requires Graphite. We're running a rather large OpenTSDB cluster to back our metrics infrastructure and would love to use that existing setup to store the data for this Grafana Plugin. 

Is there a roadmap to supporting  other backends?

**Comment by daniellee** [comment]
Hi Jared,

We have no current plans to support other data sources in the next 2-3 months. We built this app to monitor our own Kubernetes clusters hence the choice of graphite. It would not be very easy to add support for other data sources as the dashboards and one of the custom panels are tied to graphite. 

Lots of the parts are reusable for other data sources. A lot of the work was writing the [Kubestate collector](https://github.com/raintank/snap-plugin-collector-kubestate) for collecting Kubernetes data. The snap task in the app publishes to Graphite using the Snap graphite publisher plugin but there are publishers for most tsdbs including one for [OpenTSDB](https://github.com/intelsdi-x/snap-plugin-publisher-opentsdb). And all the other snap collectors are also data source agnostic. 

The collector and publisher plugins are bundled together in this [docker container](https://github.com/raintank/snap_k8s). We could add more publishers if anyone wants to use it for publishing to other data sources.

Our recommendation right now is to either fork the repo or to use the collectors and build your own dashboards.

//Daniel

**Comment by jaredledvina** [comment]
Hey Daniel, 

Thanks for all the advice! Totally understand, if this changes in the future I'd be thrilled to test it.
