### ISSUE TITLE
Container cpu and memory 0 on gke

### ISSUE THREAD

**Issue by amitgilad3** [raintank/kubernetes-app#29]
I have a kubernetes cluster deployed on google container engine with  graphite and grafana working.
i receive all the metrics but container cpu and memory are always 0 .
any ideas?

**Comment by daniellee** [comment]
Are you getting any metrics with values or is it just cpu and memory that are always 0? 

You could try undeploying and deploying the docker container with the snap collectors. There is an Undeploy button on the cluster config page.

**Comment by amitgilad3** [comment]
yes ,i get all metrics  except cpu and memory 
<img width="1347" alt="screen shot 2017-02-12 at 7 36 34 pm" src="https://cloud.githubusercontent.com/assets/7702311/22864462/b5463c34-f15a-11e6-88f5-f8430c60491a.png">

i undeployed and deployed again but still no cpu and memory

**Comment by daniellee** [comment]
Sorry for the delay. Can you give me a few details about the containers you are trying to monitor:

- Kubernetes version
- Docker/rkt
- Container OS version, or is it a container that I can download and test myself?

You could also get some log data and snap task data by running the following commands:

First get the snap pod (or pods if you have multiple nodes) name with:

`kubectl get pods -n kube-system`

Check if the task is running with (replace xxxx with the guid):

`kubectl exec -it snap-xxxxx-n kube-system -- /opt/snap/bin/snaptel task list`

And then get the logs with:

`kubectl logs snap-xxxxx -n kube-system`

**Comment by amitgilad3** [comment]
I deployed kubernetes on google container engine version 1.5.2

kubectl exec output:
e485047f-7e89-461c-b3e0-963be6d4511b 	 Task-e485047f-7e89-461c-b3e0-963be6d4511b 	 Running 	 4K 	 0 	 1 	 8:54PM 2-20-2017 	 CollectMetrics call error : time out (cmd:iostat args:[-c -d -p -g ALL -x -k -t -y 1 1])

when i check the logs i have no output 

my docker images run on ubuntu and my google vm is CONTAINER_VM provided by google

**Comment by daniellee** [comment]
Ok, that means the task is running and has succeeded 4000 times and failed just once. Can we see if the collector is collecting data. Can you run the following command and save the output. It might take up to 10 seconds before you see  something:

`kubectl exec -it snap-xxxxx -n kube-system -- /opt/snap/bin/snaptel task watch e485047f-7e89-461c-b3e0-963be6d4511b`

There will be a lot of output. We are looking for the values for the following two metrics:

- `/intel/docker/your_namespace/your_pod/your_container/stats/cgroups/cpu_stats/cpu_usage/total_usage`

- `/intel/docker/your_namespace/your_pod/your_container/stats/cgroups/memory_stats/usage/usage`

Looks like it is something to with cgroups, they are the only two metrics on the container dashboard that rely on cgroups.

**Comment by daniellee** [comment]
Wondering if this is the problem: 

- https://discuss.newrelic.com/t/docker-metrics-not-report-correctly-for-google-container-engine/36127
- https://github.com/kubernetes/kubernetes/issues/24418

**Comment by amitgilad3** [comment]
okay i ran the command and both lines  are always with a value of 0 for all pods .

i saw the link you posted and it could be the issue.
maybe you can also submit  a request to allow this

**Comment by daniellee** [comment]
There is a config option for the path to proc in the collector so I could either make it configurable or have some logic for setting the right path.

I need some more details about the docker container to be able to test this. To you have a docker file for your container or some yaml for the pod that you can share? Is the base docker container on Docker Hub or somewhere that I can download it?

**Comment by amitgilad3** [comment]
for all my applications i user docker images ubuntu  and alpine from the docker hub

thanks for the quick response and if you need anything else just let me know :)

**Comment by daniellee** [comment]
Can you be more exact? Which tags/version?

One of these or something else?
- https://hub.docker.com/r/library/ubuntu/
- https://hub.docker.com/r/library/alpine/

**Comment by daniellee** [comment]
I'll set up a test account on GKE and see if I can recreate the same error.

**Comment by daniellee** [comment]
I set up a GKE account and could see the same problem so just have to figure out how to fix it now...

**Comment by mitchhh22** [comment]
I'm experiencing the same issue on GKE.

@daniellee  Do you have any work around to fix this?

**Comment by guillelb** [comment]
I have the same problem,
Anyone know how to get those graphics (CPU & MEM)?
![image](https://user-images.githubusercontent.com/26138193/28519845-71b4e4e2-706d-11e7-9257-c94422d0c676.png)

```
/intel/docker/default/xxxx/podname/stats/cgroups/cpu_stats/cpu_usage/total_usage 			 0 			 2017-07-24 10:22:59.856914267 +0000 UTC
/intel/docker/default/xxxx/podname/stats/cgroups/memory_stats/usage/usage 				 0 			 2017-07-24 10:22:59.857416552 +0000 UTC
```

**Comment by mixecan** [comment]
Any update/workaround on this?
I'm experiencing the same issue on a kube-aws cluster running kubernetes 1.6

**Comment by guillelb** [comment]
Nothing about that?

**Comment by Dieterbe** [comment]
it seems with systemd version 226 a bunch of cgroup paths were changed
https://github.com/raintank/snap-plugin-collector-docker needs to be updated to resolve the problem.  
I think @jtlisi will work on this.

**Comment by guillelb** [comment]
Thank you for your fast response.

I use the deployment pre-configured by kubernetes-app:

Do I need to change this image version?

**snap-daemonset & snap-kubestate use:** 
```
            "image": "raintank/snap_k8s:v21",
```

**Comment by Dieterbe** [comment]
we're still in the process of fixing it. the bugfix is not ready yet.

**Comment by nimitgarg** [comment]
Any update on this? I am also facing same issue.

**Comment by puttpotsawee** [comment]
@Dieterbe @jtlisi Is there any update on this issue? I spent my last two days trying to deploy this just to discover that the CPU and Memory no longer work.
You guys can update the ongoing progress and maybe I can help fix this issue.

**Comment by Dieterbe** [comment]
afaik this is fixed. but @jtlisi has the answers.

**Comment by jtlisi** [comment]
@puttpotsawee Are you sure you deployed the master branch of the kubernetes-app? Redeploying the collectors and re-importing the dashboards. There is instructions to do so in the README. Also if you need additional help feel free to ping me in [our slack](http://slack.raintank.io/) my user-name is jlisi.

**Comment by puttpotsawee** [comment]
@jtlisi I think I deployed it right! I used `GF_INSTALL_PLUGINS` in Grafana [Official Docker](https://hub.docker.com/r/grafana/grafana/) to install the plugin, the plugin was already installed when grafana first started. I have some troubles connecting Kubernetes and Graphite but they worked just fine now. All metrics are visible on the dashboard except the Container CPU and Memory which remain 0 forever. Even the pods filter and Kubernetes tags display perfectly.

 There's no error in any `Snap` pods also. Have I configured it right? How do I make sure the kubernetes-app is in the master branch?

**Comment by Locus99** [comment]
You are likely still installing version 0.0.7.  To install version 0.0.8, you will need to install it manually.  You will need to download the master branch and zip it up.  You can then use the instructions on http://docs.grafana.org/plugins/installation/ to manually install the plug-in from a file.  If you are running grafana in a container, there are a couple of options to deploying the plug-in.   You can build a new image with the plug-in installed, or you can mount the /var/lib/grafana directory to persistent storage.  The later is an option we use.  We also install using helm to deploy to our kubernetes cluster.  If you do the storage approach, you may need to restart your deployment for grafana to recognize the installed plug-in.

**Comment by jtlisi** [comment]
@puttpotsawee, @Locus99 is correct. You need to update your plugin to the current master branch. It is likely you have a 0.0.8 version of the plugin but it does not include commits in master. Version 0.0.8 is not currently published in out [plugin repository](https://github.com/grafana/grafana-plugin-repository)

**Comment by puttpotsawee** [comment]
@Locus99 @jtlisi Thanks! The metric is working now! Thanks for your help, I hope you publish this version to the [plugin repository](https://github.com/grafana/grafana-plugin-repository) soon so this issue can be closed 😃 .

I spent some time deploying this at the beginning to so I try to add my step to the readme in #50, I hope that would be useful to others.

**Comment by Dieterbe** [comment]
+1 can we release a new stable version ?

**Comment by guillelb** [comment]
It works on kubernetes plugin version 0.0.8

**Comment by jtlisi** [comment]
Now that version 0.0.8 is published in the plugin repo I think this issue can be closed.
