### ISSUE TITLE
Authenticating with GKE cluster

### ISSUE THREAD

**Issue by mitchhh22** [raintank/kubernetes-app#35]
Is there a more detailed tutorial to setting up the kubernetes app to a cluster running on GKE?

Google provides an Endpoint, username, password and Cluster CA certificate in their UI but no combination of them seem to work. 

Can someone point me in the direction for the additional steps required?

**Comment by travissutton** [comment]
@mitchhh22 this should work assuming you can hit your GKE instance (test by hitting `https://<endpoint>/ui` first ):

**url:** `https://<endpoint>`
**Access:** `proxy`

Check the following: `Basic Auth` & `With CA Cert`

Under `Basic Auth Details`, you can use the `username` (should be `admin`) and whatever password it has set in the GKE portal. That should get you connected. I also had to manually deploy the configurations to the cluster after I set the settings. If so, just download all 4 of them into a folder and run `kubectl apply -f .` from the folder location and it should apply all 4 files.

**Comment by mitchhh22** [comment]
@travissutton Thanks that worked with getting the cluster connected...

Unfortunately none of the graphs show any data still. Did you setup a graphite Read/Write in the Data Source Settings?

**Comment by mitchhh22** [comment]
Nvm, spun up a graphite instance and its working now.

Thanks again for your assistance! :)
