### ISSUE TITLE
Cannot use my Graphite dns alias on "Data Source Settings -> Graphite Write" setting

### ISSUE THREAD

**Issue by carlosedp** [raintank/kubernetes-app#38]
When configuring the app, I've deployed my Graphite server and created it's service.

On the Data Source Settings of the cluster, I can't use my DNS alias for the service because the snap pods could not find my graphite server. When I used the ClusterIP of the Graphite Pod, it worked.

```
[root@kube-master-1 ~]# ksvc
NAMESPACE     NAME                         CLUSTER-IP       EXTERNAL-IP        PORT(S)                                 AGE
default       grafana-grafana              10.97.17.181     <nodes>            80:11652/TCP                            1d
default       graphite                     10.105.43.138    <none>             80/TCP,2003/TCP,2004/TCP,7002/TCP       22h
default       kubernetes                   10.96.0.1        <none>             443/TCP                                 6d
kube-system   heapster                     10.98.177.210    <none>             80/TCP                                  6d
kube-system   kube-dns                     10.96.0.10       <none>             53/UDP,53/TCP                           6d
```

On grafana pod (to check the my alias is OK)

```
[root@kube-master-1 ~]# kexec grafana
Pod: grafana-grafana-1686028042-vdh6x

# ping graphite.default.svc.kube.local
PING graphite.default.svc.kube.local (10.105.43.138): 56 data bytes

# cat /etc/resolv.conf
nameserver 10.96.0.10
search default.svc.kube.local svc.kube.local kube.local openstacklocal
options ndots:5
```

On snap pod (to check it does not resolve the name)

```
[root@kube-master-1 ~]# kexec snap
Pod: snap-b8559

root@kube-master-1:/#
root@kube-master-1:/# ping graphite.default.svc.kube.local
bash: ping: command not found
root@kube-master-1:/# curl graphite.default.svc.kube.local
curl: (6) Could not resolve host: graphite.default.svc.kube.local
```

It appears that when I drop into the pod, I go into one of my minions so it doesn't resolve using Kubernetes own DNS.

**Comment by jbrehm** [comment]
This is annoying, but it's because docker allows you to set a container to have hostnetwork which will force the container to also use the host's DNS servers.  So you can't use the kube-dns servers inside this container.  Discussion is here: https://github.com/kubernetes/kubernetes/issues/17406

**Comment by woodsaj** [comment]
The kubernetes-app PODs need to run with hostNetwork=true so that they can collect stats from all of the network interfaces.

So instead of setting the "graphite Write" address to graphite.default.svc.kube.local, just set it to the clusterIP address (10.105.43.138)
