### ISSUE TITLE
No way to update snap-tasks Config Map in Kubernetes

### ISSUE THREAD

**Issue by daniellee** [raintank/kubernetes-app#5]
If you change the carbon fields in the Cluster Config, the the snap-tasks Config Map in the Kubernetes cluster doesn't get updated.

Having the Deploy button for a one-time deploy of the snap-tasks to Kubernetes as well as having a Save button is bit clunky. Maybe it should deploy or update the snap-tasks config map on Save.

**Comment by woodsaj** [comment]
We could certainly give more controll to the user over the "task" manifest that is stored in kubernetes as a configMap.   Having the app push an updated ConfigMap to K8s should be fairly straight forward.
However I dont think that just pushing the configMap to k8s have any impact on the pods that are already running.

So my suggestions are:
1) Have the app pull the current confgMap from k8s if it already exists.
2) allow the user to modify the task. Initially this will just be the publisher config (graphite address and prefix)
3) When the task manifest (aka configMap) is modified, push the modified version to k8s
4) work out what needs to be done to push the updated task manifest into Snap.  While not the most elegant, simply deleting all of the pods would work as k8s would then re-create them with the updated configMap.

**Comment by woodsaj** [comment]
RE the deploy button, i am all for merging the 2 buttons.  However, if the daemonset is going to be deployed to k8s i would want to make sure it is very clear to the user that we are about to deploy something on their kubernetes cluster, a "please confirm" modal popup might because.
