### ISSUE TITLE
Link to pod dashboard that doesn't exist

### ISSUE THREAD

**Issue by daniellee** [raintank/kubernetes-app#6]
On the pod overview, there is a link to a Pod Dashboard which doesn't exist (yet at least).

![pod-overview-screenshot](https://cloud.githubusercontent.com/assets/434655/19823391/9d74b22a-9d68-11e6-881e-3526770b7434.png)

**Comment by woodsaj** [comment]
I think you will just need to link to the container dashboard with the correct cluster, node and container template variables set in the url.
