### ISSUE TITLE
Mismatch between hostname and node name if --hostname-override used

### ISSUE THREAD

**Issue by daniellee** [raintank/kubernetes-app#7]
If a Kubelet is started using the --hostname-override option, then the Kubernetes node name won't match with the hostname in the Graphite metric name.

Very hard to do this automatically as the hostname override can be anything. Most often an IP address but something like `ip route get 8.8.8.8 | awk '{print $NF; exit}'` or `hostname -i` would just be guessing.

**Comment by woodsaj** [comment]
I am not sure what the problem here is?

Are you saying that the nodeName reported via in kubernetes, eg `kubectl get node` is different to the nodeName used in the metrics sent by snap?

**Comment by woodsaj** [comment]
I have commited a change to raintank/k8s_snap to allow setting the NodeName via Env vars. https://github.com/raintank/snap_k8s/commit/9da7ad230151fbd6afbd8568c68da6866e64695b

So this problem can be solved by just adding the following to the POD spec

```
env:
- name: NODE_NAME
  valueFrom:
    fieldRef:
      fieldPath: spec.nodeName
```

**Comment by daniellee** [comment]
Thanks Anthony, I'll test that now with our local Kubernetes cluster. This should work.

Just to be clear the problem is a mismatch between the override (usually an IP address) and the hostname command in the load_tasks.sh that we use in the string replace.

For example, the hostname for our local cluster is k8s-01 but Claes specified an hostname override to the IP address instead. For the snap Graphite published that means the prefix to all metric names is `snap.<clustername>.k8s-01` but the node name in k8s is 192.168.9.201.
